export const MAURITIUS_LOCATION_OPTIONS = [
  "Albion",
  "Amaury",
  "Amitie",
  "Anse La Raie",
  "Arsenal",
  "Baie du Cap",
  "Baie du Tombeau",
  "Bambous",
  "Bambous Virieux",
  "Bananes",
  "Beau Vallon",
  "Bel Air Riviere Seche",
  "Belle Mare",
  "Bel Ombre",
  "Belle Vue Haurel",
  "Benares",
  "Bois Cheri",
  "Bois des Amourettes",
  "Bon Accueil",
  "Bramsthan",
  "Brisee Verdiere",
  "Britannia",
  "Calebasses",
  "Camp Carol",
  "Camp de Masque",
  "Camp de Masque Pave",
  "Camp Diable",
  "Camp Ithier",
  "Camp Thorel",
  "Cap Malheureux",
  "Cascavelle",
  "Case Noyale",
  "Centre de Flacq",
  "Chamarel",
  "Chamouny",
  "Chemin Grenier",
  "Clemencia",
  "Cluny",
  "Congomah",
  "Cottage",
  "Creve Coeur",
  "D'Epinay",
  "Dagotiere",
  "Dubreuil",
  "Ecroignard",
  "Esperance",
  "Esperance Trebuchet",
  "Flic en Flac",
  "Fond du Sac",
  "Goodlands",
  "Grand Baie",
  "Grand Bel Air",
  "Grand Bois",
  "Grand Gaube",
  "Grand Sable",
  "Grande Retraite",
  "Grande Riviere Noire",
  "Grande Riviere Sud Est",
  "Gros Cailloux",
  "Henrietta",
  "L'Avenir",
  "L'Escalier",
  "La Flora",
  "La Gaulette",
  "La Laura-Malenga",
  "Lalmatie",
  "Laventure",
  "Le Hochet",
  "Le Morne",
  "Le Vale",
  "Mapou",
  "Mare Chicose",
  "Mare d'Albert",
  "Mare La Chaux",
  "Mare Tabac",
  "Medine Camp de Masque",
  "Melrose",
  "Midlands",
  "Montagne Blanche",
  "Montagne Longue",
  "Morcellement Saint Andre",
  "New Grove",
  "Notre Dame",
  "Nouvelle Decouverte",
  "Nouvelle France",
  "Olivia",
  "Pailles",
  "Pamplemousses",
  "Petit Bel Air",
  "Petit Raffray",
  "Petite Riviere",
  "Pitre",
  "Piton",
  "Plaine des Papayes",
  "Plaine des Roches",
  "Plaine Magnien",
  "Pointe aux Piments",
  "Poste de Flacq",
  "Poudre d'Or",
  "Poudre d'Or Hamlet",
  "Providence",
  "Quartier Militaire",
  "Quatre Cocos",
  "Quatre Soeurs",
  "Queen Victoria",
  "Richelieu",
  "Ripailles",
  "Riviere des Anguilles",
  "Riviere des Creoles",
  "Riviere du Poste",
  "Riviere du Rempart",
  "Roche Terre",
  "Roches Noires",
  "Rose Belle",
  "Saint Aubin",
  "Saint Hubert",
  "Saint Julien Village",
  "Saint Julien d'Hotman",
  "Saint Pierre",
  "Sebastopol",
  "Seizieme Mille",
  "Souillac",
  "Surinam",
  "Tamarin",
  "Terre Rouge",
  "Triolet",
  "Trois Boutiques",
  "Trou aux Biches",
  "Trou d'Eau Douce",
  "Tyack",
  "Union Park",
  "Vale",
  "Verdun",
  "Vieux Grand Port",
  "Ville Bague",
];
